/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mydigitalschool.tp3;

import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.MongoIterable;
import com.mydigitalschool.mongodb.MongoService;
import com.mydigitalschool.tools.Scan;
import com.mydigitalschool.user.MongoUserManager;
import com.mongodb.client.MongoClient;
import com.mongodb.MongoClientSettings;
import com.mongodb.ServerAddress;

import java.util.Arrays;
import java.util.Scanner;

import org.bson.Document;
import com.mydigitalschool.mongodb.MongoService;

public class App {
	  public String getGreeting() {
	    return "Hello world.";
	  }

	  public static void main(String[] args) throws Exception {
	    System.out.println(new App().getGreeting());

	    String host = "127.0.0.1";
	    Integer port = 27017;
	    String database = "";

	    for (int i = 0; i < args.length; i++) {
	      if (args[i].startsWith("--")) {
	        if (args[i].equals("--host")) {
	          if (i + 1 < args.length && !args[i + 1].startsWith("--")) {
	            host = args[i+1];
	          }else {
	            throw new Exception("--host not defined");
	          }
	        }
	        if (args[i].equals("--port")) {
	          if (i + 1 < args.length && !args[i + 1].startsWith("--")) {
	            try {
	              port = Integer.parseInt(args[i+1]);
	            } catch (NumberFormatException e) {
	              throw e;
	            }
	          }else {
	            throw new Exception("--port not defined");
	          }
	        }
	        if (args[i].equals("--db")) {
	          if (i + 1 < args.length && !args[i + 1].startsWith("--")) {
	            database = args[i+1];
	          }else {
	            throw new Exception("--db not defined");
	          }
	        }
	      }
	    }

	    MongoService service = new MongoService(host, port);
	    MongoDatabase db = service.getMongoClient().getDatabase(database);
	    new MongoUserManager(db).run();

	    System.out.println("Ended");
	  }
	}

